// Generated by npm run sync:openapi. Do not edit.
export const operationSchemas = {
  "get_api_credit_usage": {
    "query": [],
    "body": []
  },
  "get_ai_credit_usage": {
    "query": [],
    "body": []
  },
  "list_ai_credit_events": {
    "query": [
      {
        "name": "cursor",
        "type": "string",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ],
    "body": []
  },
  "get_email_usage": {
    "query": [],
    "body": []
  },
  "list_workspaces": {
    "query": [],
    "body": []
  },
  "get_workspace": {
    "query": [],
    "body": []
  },
  "update_workspace": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "timezone",
        "type": [
          "string",
          "null"
        ],
        "required": false,
        "description": "IANA timezone, or null to clear"
      }
    ]
  },
  "get_workspace_storage": {
    "query": [],
    "body": []
  },
  "list_workspace_members": {
    "query": [],
    "body": []
  },
  "update_member_role": {
    "query": [],
    "body": [
      {
        "name": "role",
        "type": "string",
        "required": true,
        "values": [
          "admin",
          "member"
        ]
      }
    ]
  },
  "remove_workspace_member": {
    "query": [],
    "body": []
  },
  "invite_workspace_member": {
    "query": [],
    "body": [
      {
        "name": "email",
        "type": "string",
        "required": true
      },
      {
        "name": "role",
        "type": "string",
        "required": false,
        "values": [
          "admin",
          "member"
        ]
      }
    ]
  },
  "resend_workspace_invite": {
    "query": [],
    "body": []
  },
  "list_email_domains": {
    "query": [],
    "body": []
  },
  "add_email_domain": {
    "query": [],
    "body": [
      {
        "name": "domain",
        "type": "string",
        "required": true,
        "description": "Custom subdomain used for agent mailboxes"
      }
    ]
  },
  "delete_email_domain": {
    "query": [],
    "body": []
  },
  "verify_email_domain": {
    "query": [],
    "body": []
  },
  "list_workspace_mailboxes": {
    "query": [],
    "body": []
  },
  "list_mailboxes": {
    "query": [
      {
        "name": "workspaceId",
        "type": "string",
        "required": false,
        "description": "Optional for session clients; workspace-scoped credentials use their bound workspace."
      }
    ],
    "body": []
  },
  "create_mailbox": {
    "query": [],
    "body": [
      {
        "name": "email",
        "type": "string",
        "required": true,
        "description": "Address on an allowed hosted or fully verified custom domain."
      },
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Human-readable mailbox display name."
      },
      {
        "name": "workspaceId",
        "type": "string",
        "required": false,
        "description": "Optional for workspace-scoped API keys; if supplied it must match the credential workspace."
      },
      {
        "name": "settings",
        "type": "object",
        "required": false,
        "description": "Optional mailbox settings. For a dedicated verification inbox, use agentInbox.mode=verification and agentInbox.automationsEnabled=false."
      }
    ]
  },
  "get_mailbox": {
    "query": [],
    "body": []
  },
  "update_mailbox_settings": {
    "query": [],
    "body": [
      {
        "name": "settings",
        "type": "object",
        "required": true,
        "description": "Full settings object to store on the mailbox"
      }
    ]
  },
  "get_mailbox_storage": {
    "query": [],
    "body": []
  },
  "list_emails": {
    "query": [
      {
        "name": "folder",
        "type": "string",
        "required": false,
        "description": "Use inbox for inbound verification messages."
      },
      {
        "name": "page",
        "type": "integer",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      },
      {
        "name": "sortColumn",
        "type": "string",
        "required": false,
        "values": [
          "id",
          "subject",
          "sender",
          "recipient",
          "date",
          "read",
          "starred"
        ]
      },
      {
        "name": "sortDirection",
        "type": "string",
        "required": false,
        "values": [
          "ASC",
          "DESC"
        ]
      },
      {
        "name": "include_held",
        "type": "boolean",
        "required": false,
        "description": "Include mail held by auto-draft. Use only for the active verification flow."
      },
      {
        "name": "metadata_only",
        "type": "boolean",
        "required": false,
        "description": "Omit body, snippet, raw headers, and threat URLs while establishing a baseline or correlating candidates."
      },
      {
        "name": "require_scan_status",
        "type": "string",
        "required": false,
        "description": "Require an exact stored scan status. Prefer clean before exposing content to an agent.",
        "values": [
          "clean",
          "flagged",
          "skipped"
        ]
      },
      {
        "name": "agent_safe_content",
        "type": "boolean",
        "required": false,
        "description": "Omit raw headers, provider metadata, threat details, attachment metadata, and storage diagnostics; normalize untrusted text fields to bounded plain text."
      }
    ],
    "body": []
  },
  "send_email": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": true
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "from",
        "type": "json",
        "required": true
      },
      {
        "name": "subject",
        "type": "string",
        "required": true
      },
      {
        "name": "html",
        "type": "string",
        "required": false,
        "description": "Rich email body. When html and text are both supplied, both MIME alternatives are delivered and html is stored for display."
      },
      {
        "name": "text",
        "type": "string",
        "required": false,
        "description": "Literal plain-text body. Newlines and repeated spaces are preserved; Markdown is not rendered."
      },
      {
        "name": "attachments",
        "type": "array",
        "required": false,
        "description": "Base64 file bytes or an existing attachment_id from the same authorized mailbox. Omit to preserve attachments from source_draft_id (send) or draft_id (save/schedule); [] clears; an array replaces the complete set. Storage limits: 20 files, 10 MiB each, 25 MiB decoded total. Provider message limits include encoding/overhead: Cloudflare 5 MiB, Resend 40 MB. Reject empty files, unsafe filenames, malformed base64, duplicate references and Content-IDs. Base64 adds about one third in transport size; reverse proxy limits also apply. Local paths and URLs are not accepted."
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "references",
        "type": "array",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "source_draft_id",
        "type": "string",
        "required": false
      },
      {
        "name": "client_send_id",
        "type": "string",
        "required": false
      }
    ]
  },
  "get_email": {
    "query": [
      {
        "name": "include_held",
        "type": "boolean",
        "required": false,
        "description": "Read a held message only for the active verification flow."
      },
      {
        "name": "metadata_only",
        "type": "boolean",
        "required": false,
        "description": "Omit body, snippet, raw headers, and threat URLs."
      },
      {
        "name": "action_metadata_only",
        "type": "boolean",
        "required": false,
        "description": "Omit message content and include bounded, server-derived reply_targets for safe action preflight."
      },
      {
        "name": "require_scan_status",
        "type": "string",
        "required": false,
        "description": "Expose the body only when the stored scan status exactly matches. Existing mismatches return safe metadata with content_omitted=true.",
        "values": [
          "clean",
          "flagged",
          "skipped"
        ]
      },
      {
        "name": "max_body_chars",
        "type": "integer",
        "required": false,
        "description": "Cap the returned body length without mutating the stored message."
      },
      {
        "name": "agent_safe_content",
        "type": "boolean",
        "required": false,
        "description": "Omit raw headers, provider metadata, threat details, attachment metadata, and storage diagnostics; normalize untrusted text fields to bounded plain text."
      }
    ],
    "body": []
  },
  "get_email_context": {
    "query": [
      {
        "name": "limit",
        "type": "integer",
        "required": false
      },
      {
        "name": "cursor",
        "type": "string",
        "required": false,
        "description": "Opaque next_cursor from the preceding context page."
      },
      {
        "name": "include_held",
        "type": "boolean",
        "required": false,
        "description": "Include mail held by auto-draft only for the active verification flow."
      }
    ],
    "body": []
  },
  "update_email": {
    "query": [],
    "body": [
      {
        "name": "read",
        "type": "boolean",
        "required": false
      },
      {
        "name": "starred",
        "type": "boolean",
        "required": false
      }
    ]
  },
  "delete_email": {
    "query": [
      {
        "name": "permanent",
        "type": "boolean",
        "required": false,
        "description": "Set to `true` to permanently delete instead of moving to trash"
      }
    ],
    "body": []
  },
  "bulk_delete_emails": {
    "query": [],
    "body": [
      {
        "name": "ids",
        "type": "array",
        "required": true
      },
      {
        "name": "permanent",
        "type": "boolean",
        "required": false,
        "description": "Hard-delete when true"
      }
    ]
  },
  "bulk_mark_emails_read": {
    "query": [],
    "body": [
      {
        "name": "ids",
        "type": "array",
        "required": true
      },
      {
        "name": "read",
        "type": "boolean",
        "required": true
      }
    ]
  },
  "bulk_move_emails": {
    "query": [],
    "body": [
      {
        "name": "ids",
        "type": "array",
        "required": true
      },
      {
        "name": "folderId",
        "type": "string",
        "required": true
      }
    ]
  },
  "move_email": {
    "query": [],
    "body": [
      {
        "name": "folderId",
        "type": "string",
        "required": true
      }
    ]
  },
  "reply_to_email": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": true
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "from",
        "type": "json",
        "required": true
      },
      {
        "name": "subject",
        "type": "string",
        "required": true
      },
      {
        "name": "html",
        "type": "string",
        "required": false,
        "description": "Rich email body. When html and text are both supplied, both MIME alternatives are delivered and html is stored for display."
      },
      {
        "name": "text",
        "type": "string",
        "required": false,
        "description": "Literal plain-text body. Newlines and repeated spaces are preserved; Markdown is not rendered."
      },
      {
        "name": "attachments",
        "type": "array",
        "required": false,
        "description": "Base64 file bytes or an existing attachment_id from the same authorized mailbox. Omit to preserve attachments from source_draft_id (send) or draft_id (save/schedule); [] clears; an array replaces the complete set. Storage limits: 20 files, 10 MiB each, 25 MiB decoded total. Provider message limits include encoding/overhead: Cloudflare 5 MiB, Resend 40 MB. Reject empty files, unsafe filenames, malformed base64, duplicate references and Content-IDs. Base64 adds about one third in transport size; reverse proxy limits also apply. Local paths and URLs are not accepted."
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "references",
        "type": "array",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "source_draft_id",
        "type": "string",
        "required": false
      },
      {
        "name": "client_send_id",
        "type": "string",
        "required": false
      }
    ]
  },
  "forward_email": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": true
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "from",
        "type": "json",
        "required": true
      },
      {
        "name": "subject",
        "type": "string",
        "required": true
      },
      {
        "name": "html",
        "type": "string",
        "required": false,
        "description": "Rich email body. When html and text are both supplied, both MIME alternatives are delivered and html is stored for display."
      },
      {
        "name": "text",
        "type": "string",
        "required": false,
        "description": "Literal plain-text body. Newlines and repeated spaces are preserved; Markdown is not rendered."
      },
      {
        "name": "attachments",
        "type": "array",
        "required": false,
        "description": "Base64 file bytes or an existing attachment_id from the same authorized mailbox. Omit to preserve attachments from source_draft_id (send) or draft_id (save/schedule); [] clears; an array replaces the complete set. Storage limits: 20 files, 10 MiB each, 25 MiB decoded total. Provider message limits include encoding/overhead: Cloudflare 5 MiB, Resend 40 MB. Reject empty files, unsafe filenames, malformed base64, duplicate references and Content-IDs. Base64 adds about one third in transport size; reverse proxy limits also apply. Local paths and URLs are not accepted."
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "references",
        "type": "array",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "source_draft_id",
        "type": "string",
        "required": false
      },
      {
        "name": "client_send_id",
        "type": "string",
        "required": false
      }
    ]
  },
  "download_attachment": {
    "query": [],
    "body": []
  },
  "save_draft": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": false
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "subject",
        "type": "string",
        "required": false
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "description": "Body bytes stored without rewriting. Use body_format=text for literal whitespace or body_format=html for rich email markup. Markdown is not rendered automatically."
      },
      {
        "name": "body_format",
        "type": "string",
        "required": false,
        "description": "How the body must be delivered and rendered. \"text\" preserves literal whitespace and does not interpret Markdown; \"html\" enables rich formatting subject to email sanitization.",
        "values": [
          "html",
          "text"
        ]
      },
      {
        "name": "attachments",
        "type": "array",
        "required": false,
        "description": "Base64 file bytes or an existing attachment_id from the same authorized mailbox. Omit to preserve attachments from source_draft_id (send) or draft_id (save/schedule); [] clears; an array replaces the complete set. Storage limits: 20 files, 10 MiB each, 25 MiB decoded total. Provider message limits include encoding/overhead: Cloudflare 5 MiB, Resend 40 MB. Reject empty files, unsafe filenames, malformed base64, duplicate references and Content-IDs. Base64 adds about one third in transport size; reverse proxy limits also apply. Local paths and URLs are not accepted."
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "draft_id",
        "type": "string",
        "required": false
      }
    ]
  },
  "regenerate_draft": {
    "query": [],
    "body": [
      {
        "name": "draftId",
        "type": "string",
        "required": true
      },
      {
        "name": "prompt",
        "type": "string",
        "required": true
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "description": "Current draft HTML/body to revise"
      }
    ]
  },
  "schedule_email_send": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": true
      },
      {
        "name": "scheduled_send_at",
        "type": "string",
        "required": true
      }
    ]
  },
  "empty_trash": {
    "query": [],
    "body": []
  },
  "get_thread": {
    "query": [],
    "body": []
  },
  "mark_thread_read": {
    "query": [],
    "body": []
  },
  "list_folders": {
    "query": [],
    "body": []
  },
  "create_folder": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      }
    ]
  },
  "update_folder": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      }
    ]
  },
  "delete_folder": {
    "query": [],
    "body": []
  },
  "search_emails": {
    "query": [
      {
        "name": "query",
        "type": "string",
        "required": false
      },
      {
        "name": "from",
        "type": "string",
        "required": false
      },
      {
        "name": "to",
        "type": "string",
        "required": false
      },
      {
        "name": "subject",
        "type": "string",
        "required": false
      },
      {
        "name": "date_start",
        "type": "string",
        "required": false
      },
      {
        "name": "date_end",
        "type": "string",
        "required": false
      },
      {
        "name": "folder",
        "type": "string",
        "required": false
      },
      {
        "name": "require_scan_status",
        "type": "string",
        "required": false,
        "description": "Require an exact stored scan status. Prefer clean before reading verification content.",
        "values": [
          "clean",
          "flagged",
          "skipped"
        ]
      },
      {
        "name": "include_held",
        "type": "boolean",
        "required": false,
        "description": "Include mail held by auto-draft. Use only for the active verification flow."
      },
      {
        "name": "metadata_only",
        "type": "boolean",
        "required": false,
        "description": "Omit body, snippet, raw headers, and threat URLs while correlating candidates."
      },
      {
        "name": "agent_safe_content",
        "type": "boolean",
        "required": false,
        "description": "Omit raw headers, provider metadata, threat details, attachment metadata, and storage diagnostics; normalize untrusted text fields to bounded plain text."
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ],
    "body": []
  },
  "list_custom_labels": {
    "query": [],
    "body": []
  },
  "create_custom_label": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": true
      },
      {
        "name": "rules",
        "type": "string",
        "required": true,
        "description": "Label matching rules text"
      },
      {
        "name": "color",
        "type": [
          "string",
          "null"
        ],
        "required": false,
        "description": "Optional hex color"
      }
    ]
  },
  "update_custom_label": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "rules",
        "type": "string",
        "required": false
      },
      {
        "name": "color",
        "type": [
          "string",
          "null"
        ],
        "required": false
      }
    ]
  },
  "delete_custom_label": {
    "query": [],
    "body": []
  },
  "list_agent_conversations": {
    "query": [],
    "body": []
  },
  "create_agent_conversation": {
    "query": [],
    "body": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Required when creating a normal chat if provided; 1–80 chars"
      },
      {
        "name": "threadId",
        "type": "string",
        "required": false,
        "description": "When set, finds or creates the thread-linked conversation (title optional; defaults to “(No subject)”)"
      }
    ]
  },
  "rename_agent_conversation": {
    "query": [],
    "body": [
      {
        "name": "title",
        "type": "string",
        "required": true
      }
    ]
  },
  "delete_agent_conversation": {
    "query": [],
    "body": []
  },
  "list_agent_messages": {
    "query": [
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "description": "Page size (1–50, default 50)"
      },
      {
        "name": "cursor",
        "type": "string",
        "required": false,
        "description": "Opaque cursor from a previous `nextCursor` value"
      }
    ],
    "body": []
  },
  "chat_with_mailbox_agent": {
    "query": [],
    "body": [
      {
        "name": "mailboxId",
        "type": "string",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "required": true
      },
      {
        "name": "messages",
        "type": "array",
        "required": true,
        "description": "AI SDK UIMessage array (id, role, parts)"
      },
      {
        "name": "thread_id",
        "type": [
          "string",
          "null"
        ],
        "required": false
      },
      {
        "name": "trigger",
        "type": "string",
        "required": false,
        "values": [
          "submit-message",
          "regenerate-message"
        ]
      }
    ]
  },
  "list_task_triagers": {
    "query": [],
    "body": []
  },
  "create_task_triager": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "instructions",
        "type": "string",
        "required": false,
        "description": "Required non-empty instructions for create/update"
      },
      {
        "name": "triggers",
        "type": "array",
        "required": false,
        "description": "At least one trigger is required"
      },
      {
        "name": "tasks",
        "type": "array",
        "required": false
      }
    ]
  },
  "list_recent_triager_runs": {
    "query": [
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "description": "Max runs to return (1–20, default 10)"
      }
    ],
    "body": []
  },
  "update_task_triager": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "instructions",
        "type": "string",
        "required": false,
        "description": "Required non-empty instructions for create/update"
      },
      {
        "name": "triggers",
        "type": "array",
        "required": false,
        "description": "At least one trigger is required"
      },
      {
        "name": "tasks",
        "type": "array",
        "required": false
      }
    ]
  },
  "delete_task_triager": {
    "query": [],
    "body": []
  },
  "get_or_create_triager_conversation": {
    "query": [],
    "body": []
  },
  "list_composio_toolkits": {
    "query": [],
    "body": []
  },
  "connect_composio_toolkit": {
    "query": [],
    "body": [
      {
        "name": "callbackUrl",
        "type": "string",
        "required": false
      },
      {
        "name": "authMethod",
        "type": "string",
        "required": false,
        "values": [
          "oauth",
          "api_key"
        ]
      },
      {
        "name": "apiKey",
        "type": "string",
        "required": false
      }
    ]
  },
  "disconnect_composio_toolkit": {
    "query": [],
    "body": []
  },
  "list_composio_connections": {
    "query": [],
    "body": []
  },
  "sync_composio_connections": {
    "query": [],
    "body": []
  },
  "search_composio_tools": {
    "query": [],
    "body": []
  },
  "get_composio_tool_schema": {
    "query": [],
    "body": []
  },
  "execute_composio_tool": {
    "query": [],
    "body": [
      {
        "name": "slug",
        "type": "string",
        "required": true
      },
      {
        "name": "arguments",
        "type": "object",
        "required": false
      },
      {
        "name": "connectedAccountId",
        "type": "string",
        "required": false
      }
    ]
  },
  "get_composio_calendar_account": {
    "query": [],
    "body": []
  }
} as const;
