// Generated by npm run sync:openapi. Do not edit.
export const operationSchemas = {
  "get_api_credit_usage": {
    "query": [],
    "body": []
  },
  "get_email_usage": {
    "query": [],
    "body": []
  },
  "list_workspaces": {
    "query": [],
    "body": []
  },
  "get_workspace": {
    "query": [],
    "body": []
  },
  "update_workspace": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "timezone",
        "type": "string",
        "required": false,
        "description": "IANA timezone, or null to clear"
      }
    ]
  },
  "delete_workspace": {
    "query": [],
    "body": []
  },
  "get_workspace_storage": {
    "query": [],
    "body": []
  },
  "list_workspace_members": {
    "query": [],
    "body": []
  },
  "update_member_role": {
    "query": [],
    "body": [
      {
        "name": "role",
        "type": "string",
        "required": true,
        "values": [
          "admin",
          "member"
        ]
      }
    ]
  },
  "remove_workspace_member": {
    "query": [],
    "body": []
  },
  "invite_workspace_member": {
    "query": [],
    "body": [
      {
        "name": "email",
        "type": "string",
        "required": true
      },
      {
        "name": "role",
        "type": "string",
        "required": false,
        "values": [
          "admin",
          "member"
        ]
      }
    ]
  },
  "resend_workspace_invite": {
    "query": [],
    "body": []
  },
  "list_email_domains": {
    "query": [],
    "body": []
  },
  "add_email_domain": {
    "query": [],
    "body": [
      {
        "name": "domain",
        "type": "string",
        "required": true,
        "description": "Custom subdomain used for agent mailboxes"
      }
    ]
  },
  "delete_email_domain": {
    "query": [],
    "body": []
  },
  "verify_email_domain": {
    "query": [],
    "body": []
  },
  "list_workspace_mailboxes": {
    "query": [],
    "body": []
  },
  "list_mailboxes": {
    "query": [
      {
        "name": "workspaceId",
        "type": "string",
        "required": false,
        "description": "Filter by workspace id (session users). API keys ignore cross-workspace values and stay on the key’s workspace."
      }
    ],
    "body": []
  },
  "create_mailbox": {
    "query": [],
    "body": [
      {
        "name": "email",
        "type": "string",
        "required": true,
        "description": "Mailbox address on an allowed Mermail or custom domain"
      },
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Display name (also seeds settings.fromName)"
      },
      {
        "name": "workspaceId",
        "type": "string",
        "required": true,
        "description": "Required for `POST /api/v1/mailboxes`"
      },
      {
        "name": "settings",
        "type": "object",
        "required": false,
        "description": "Optional mailbox settings merged over defaults"
      }
    ]
  },
  "get_mailbox": {
    "query": [],
    "body": []
  },
  "update_mailbox_settings": {
    "query": [],
    "body": [
      {
        "name": "settings",
        "type": "object",
        "required": true,
        "description": "Full settings object to store on the mailbox"
      }
    ]
  },
  "get_mailbox_storage": {
    "query": [],
    "body": []
  },
  "list_emails": {
    "query": [
      {
        "name": "folder",
        "type": "string",
        "required": false,
        "description": "Folder id"
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false,
        "description": "Filter by thread id"
      },
      {
        "name": "category",
        "type": "string",
        "required": false,
        "description": "Email category",
        "values": [
          "customer_support",
          "technical",
          "partnership",
          "other"
        ]
      },
      {
        "name": "custom_label",
        "type": "string",
        "required": false,
        "description": "Custom label slug"
      },
      {
        "name": "is_starred",
        "type": "string",
        "required": false,
        "description": "true/1 or false/0"
      },
      {
        "name": "is_read",
        "type": "string",
        "required": false,
        "description": "true/1 or false/0"
      },
      {
        "name": "threaded",
        "type": "string",
        "required": false,
        "description": "Set to true/1 to aggregate by thread"
      },
      {
        "name": "page",
        "type": "integer",
        "required": false,
        "description": "Page number (≥1)"
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "description": "Page size (1–100, default 25)"
      },
      {
        "name": "sortColumn",
        "type": "string",
        "required": false,
        "description": "Sort column",
        "values": [
          "id",
          "subject",
          "sender",
          "recipient",
          "date",
          "read",
          "starred"
        ]
      },
      {
        "name": "sortDirection",
        "type": "string",
        "required": false,
        "description": "ASC for ascending; otherwise descending"
      }
    ],
    "body": []
  },
  "send_email": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": true,
        "description": "Recipient email or list"
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "from",
        "type": "json",
        "required": true
      },
      {
        "name": "subject",
        "type": "string",
        "required": true
      },
      {
        "name": "html",
        "type": "string",
        "required": false
      },
      {
        "name": "text",
        "type": "string",
        "required": false
      },
      {
        "name": "attachments",
        "type": "array",
        "required": false
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "references",
        "type": "array",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "source_draft_id",
        "type": "string",
        "required": false
      }
    ]
  },
  "get_email": {
    "query": [],
    "body": []
  },
  "update_email": {
    "query": [],
    "body": [
      {
        "name": "read",
        "type": "boolean",
        "required": false
      },
      {
        "name": "starred",
        "type": "boolean",
        "required": false
      }
    ]
  },
  "delete_email": {
    "query": [
      {
        "name": "permanent",
        "type": "boolean",
        "required": false,
        "description": "Set to `true` to permanently delete instead of moving to trash"
      }
    ],
    "body": []
  },
  "bulk_delete_emails": {
    "query": [],
    "body": [
      {
        "name": "ids",
        "type": "array",
        "required": true
      },
      {
        "name": "permanent",
        "type": "boolean",
        "required": false,
        "description": "Hard-delete when true"
      }
    ]
  },
  "bulk_mark_emails_read": {
    "query": [],
    "body": [
      {
        "name": "ids",
        "type": "array",
        "required": true
      },
      {
        "name": "read",
        "type": "boolean",
        "required": true
      }
    ]
  },
  "bulk_move_emails": {
    "query": [],
    "body": [
      {
        "name": "ids",
        "type": "array",
        "required": true
      },
      {
        "name": "folderId",
        "type": "string",
        "required": true
      }
    ]
  },
  "move_email": {
    "query": [],
    "body": [
      {
        "name": "folderId",
        "type": "string",
        "required": true
      }
    ]
  },
  "reply_to_email": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": true,
        "description": "Recipient email or list"
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "from",
        "type": "json",
        "required": true
      },
      {
        "name": "subject",
        "type": "string",
        "required": true
      },
      {
        "name": "html",
        "type": "string",
        "required": false
      },
      {
        "name": "text",
        "type": "string",
        "required": false
      },
      {
        "name": "attachments",
        "type": "array",
        "required": false
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "references",
        "type": "array",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "source_draft_id",
        "type": "string",
        "required": false
      }
    ]
  },
  "forward_email": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": true,
        "description": "Recipient email or list"
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "from",
        "type": "json",
        "required": true
      },
      {
        "name": "subject",
        "type": "string",
        "required": true
      },
      {
        "name": "html",
        "type": "string",
        "required": false
      },
      {
        "name": "text",
        "type": "string",
        "required": false
      },
      {
        "name": "attachments",
        "type": "array",
        "required": false
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "references",
        "type": "array",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "source_draft_id",
        "type": "string",
        "required": false
      }
    ]
  },
  "download_attachment": {
    "query": [],
    "body": []
  },
  "save_draft": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "string",
        "required": false
      },
      {
        "name": "cc",
        "type": "string",
        "required": false
      },
      {
        "name": "bcc",
        "type": "string",
        "required": false
      },
      {
        "name": "subject",
        "type": "string",
        "required": false
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "description": "Draft body (HTML or plain text)"
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "draft_id",
        "type": "string",
        "required": false,
        "description": "Existing draft id to replace"
      }
    ]
  },
  "regenerate_draft": {
    "query": [],
    "body": [
      {
        "name": "draftId",
        "type": "string",
        "required": true
      },
      {
        "name": "prompt",
        "type": "string",
        "required": true
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "description": "Current draft HTML/body to revise"
      }
    ]
  },
  "schedule_email_send": {
    "query": [],
    "body": [
      {
        "name": "to",
        "type": "json",
        "required": false
      },
      {
        "name": "cc",
        "type": "json",
        "required": false
      },
      {
        "name": "bcc",
        "type": "json",
        "required": false
      },
      {
        "name": "subject",
        "type": "string",
        "required": false
      },
      {
        "name": "body",
        "type": "string",
        "required": true
      },
      {
        "name": "in_reply_to",
        "type": "string",
        "required": false
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "draft_id",
        "type": "string",
        "required": false
      },
      {
        "name": "scheduled_send_at",
        "type": "string",
        "required": true,
        "description": "Must be in the future (ISO-8601)"
      }
    ]
  },
  "empty_trash": {
    "query": [],
    "body": []
  },
  "get_thread": {
    "query": [],
    "body": []
  },
  "mark_thread_read": {
    "query": [],
    "body": []
  },
  "list_folders": {
    "query": [],
    "body": []
  },
  "create_folder": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      }
    ]
  },
  "update_folder": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      }
    ]
  },
  "delete_folder": {
    "query": [],
    "body": []
  },
  "search_emails": {
    "query": [
      {
        "name": "query",
        "type": "string",
        "required": false,
        "description": "Free-text query across subject, body, sender, recipients"
      },
      {
        "name": "folder",
        "type": "string",
        "required": false,
        "description": "Folder id filter"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Sender contains"
      },
      {
        "name": "to",
        "type": "string",
        "required": false,
        "description": "Recipient contains"
      },
      {
        "name": "subject",
        "type": "string",
        "required": false,
        "description": "Subject contains"
      },
      {
        "name": "date_start",
        "type": "string",
        "required": false,
        "description": "ISO start date"
      },
      {
        "name": "date_end",
        "type": "string",
        "required": false,
        "description": "ISO end date"
      },
      {
        "name": "is_read",
        "type": "string",
        "required": false,
        "description": "true/1 for read only"
      },
      {
        "name": "is_starred",
        "type": "string",
        "required": false,
        "description": "true/1 for starred only"
      },
      {
        "name": "category",
        "type": "string",
        "required": false,
        "description": "Category filter"
      },
      {
        "name": "has_attachment",
        "type": "string",
        "required": false,
        "description": "Truthy to require attachments"
      },
      {
        "name": "page",
        "type": "integer",
        "required": false,
        "description": "page"
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "description": "limit"
      }
    ],
    "body": []
  },
  "list_custom_labels": {
    "query": [],
    "body": []
  },
  "create_custom_label": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": true
      },
      {
        "name": "rules",
        "type": "string",
        "required": true,
        "description": "Label matching rules text"
      },
      {
        "name": "color",
        "type": "string",
        "required": false,
        "description": "Optional hex color"
      }
    ]
  },
  "update_custom_label": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "rules",
        "type": "string",
        "required": false
      },
      {
        "name": "color",
        "type": "string",
        "required": false
      }
    ]
  },
  "delete_custom_label": {
    "query": [],
    "body": []
  },
  "list_agent_conversations": {
    "query": [],
    "body": []
  },
  "create_agent_conversation": {
    "query": [],
    "body": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Required when creating a normal chat if provided; 1–80 chars"
      },
      {
        "name": "threadId",
        "type": "string",
        "required": false,
        "description": "When set, finds or creates the thread-linked conversation (title optional; defaults to “(No subject)”)"
      }
    ]
  },
  "rename_agent_conversation": {
    "query": [],
    "body": [
      {
        "name": "title",
        "type": "string",
        "required": true
      }
    ]
  },
  "delete_agent_conversation": {
    "query": [],
    "body": []
  },
  "list_agent_messages": {
    "query": [
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "description": "Page size (1–50, default 50)"
      },
      {
        "name": "cursor",
        "type": "string",
        "required": false,
        "description": "Opaque cursor from a previous `nextCursor` value"
      }
    ],
    "body": []
  },
  "chat_with_mailbox_agent": {
    "query": [],
    "body": [
      {
        "name": "mailboxId",
        "type": "string",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "required": true
      },
      {
        "name": "messages",
        "type": "array",
        "required": true,
        "description": "AI SDK UIMessage array (id, role, parts)"
      },
      {
        "name": "thread_id",
        "type": "string",
        "required": false
      },
      {
        "name": "trigger",
        "type": "string",
        "required": false,
        "values": [
          "submit-message",
          "regenerate-message"
        ]
      }
    ]
  },
  "list_task_triagers": {
    "query": [],
    "body": []
  },
  "create_task_triager": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "instructions",
        "type": "string",
        "required": false,
        "description": "Required non-empty instructions for create/update"
      },
      {
        "name": "triggers",
        "type": "array",
        "required": false,
        "description": "At least one trigger is required"
      },
      {
        "name": "tasks",
        "type": "array",
        "required": false
      }
    ]
  },
  "list_recent_triager_runs": {
    "query": [
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "description": "Max runs to return (1–20, default 10)"
      }
    ],
    "body": []
  },
  "update_task_triager": {
    "query": [],
    "body": [
      {
        "name": "name",
        "type": "string",
        "required": false
      },
      {
        "name": "instructions",
        "type": "string",
        "required": false,
        "description": "Required non-empty instructions for create/update"
      },
      {
        "name": "triggers",
        "type": "array",
        "required": false,
        "description": "At least one trigger is required"
      },
      {
        "name": "tasks",
        "type": "array",
        "required": false
      }
    ]
  },
  "delete_task_triager": {
    "query": [],
    "body": []
  },
  "set_default_task_triager": {
    "query": [],
    "body": []
  },
  "get_or_create_triager_conversation": {
    "query": [],
    "body": []
  }
} as const;
